#!/bin/sh

#test="apt-get update -y && apt-get upgrade -y && apt-get install -y gcc git"

#docker run -it --rm --name myshell debian /bin/sh -c "$test"
docker run -it --rm --name myshell debian sh -c "`cat 09`"
